export {default as assetPlugin} from "./asset";
export {default as backgroundPlugin} from "./background";
export {default as contentPlugin} from "./content";
export {default as dotenvPlugin} from "./dotenv";
export {default as htmlPlugin} from "./html";
export {default as iconPlugin} from "./icon";
export {default as localePlugin} from "./locale";
export {default as metaPlugin} from "./meta";
export {default as offscreenPlugin} from "./offscreen";
export {default as pagePlugin} from "./page";
export {default as popupPlugin} from "./popup";
export {default as publicPlugin} from "./public";
export {default as sidebarPlugin} from "./sidebar";
export {default as typescriptPlugin, TypescriptConfig, FileBuilder, VendorDeclaration} from "./typescript";
export {default as reactPlugin} from "./react";
export {default as stylePlugin} from "./style";
export {default as viewPlugin} from "./view";
export {default as versionPlugin} from "./version";
