import {getUrl} from "@browser/runtime";

import {PageConfig, PageDefinition, PageProps} from "@typing/page";

export type {PageDefinition, PageProps, PageConfig};

export type PageAlias = string;

export type PageMap = Map<PageAlias, string>;

export const definePage = (options: PageDefinition): PageDefinition => {
    return options;
};

export const getPages = (): PageMap => {
    const pages: PageMap = new Map();

    try {
        // @ts-expect-error: PAGE_ALIAS is a virtual variable generated by the bundler `src/cli/plugins/page/index.ts`
        Object.entries<string>(PAGE_ALIAS).forEach(([key, value]) => {
            pages.set(key, value);
        });
    } catch (e) {
        console.error('Error getting pages:', e);
    }

    return pages;
}

export const getPageUrl = (alias: PageAlias): string => {
    let path = getPages().get(alias);

    if (!path) {
        console.warn(`Cannot find page: ${alias}`);

        path = alias;
    }

    return getUrl(path);
}